# oc create -f databases-crd.yaml --as=system:admin                 :   Register the CRD with OCP; note:  this occurs asynchroneously
# oc get crd databases.example.com -o yaml --as=system:admin        :   check the status of the new CRD

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.example.com
spec:
  group: example.com
  version: v1
  names:
    kind: Database
    plural: databases
  scope: Namespaced
