apiVersion: v1
kind: PersistentVolume
metadata:
  name: {name}
spec:
  capacity:
    storage: 10Gi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /{path}
    server: 192.168.122.1
  persistentVolumeReclaimPolicy: Retain
