---

- name: oc test
  shell: |
      oc get project

- name: set fact test
  shell: |
    oc whoami --show-server
  register: ocp_master_url

- debug:
    msg: "ocp_master_url = {{ ocp_master_url.stdout }}"

- name: oc test impersonate system admin
  shell: |
      oc get nodes --as=system:admin

- name: pad numbers
  set_fact:
    item: "1"
- debug: msg={{ 'Item\:\ %02d'|format(item|int) }}

- set_fact:
    my_pass: "{{ lookup('password', '/dev/null chars=ascii_letters length=32') }}"
- debug:
    msg: "my_pass: {{ my_pass }}"
