apiVersion: v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
        - env:
            - name: CATALOG_ENDPOINT
              value: ${CATALOG_ENDPOINT}
            - name: INVENTORY_ENDPOINT
              value: ${INVENTORY_ENDPOINT}
            - name: CART_ENDPOINT
              value: ${CART_ENDPOINT}
