spec:
  template:
    spec:
      containers:
        - env:
          - name: catalog_service_url
            valueFrom:
              configMapKeyRef:
                name: cart-config
                key: catalog_service_url
