# Execution: Istio enabled
#   istioctl kube-inject -f ftools-deploy.yml > $HOME/lab/ftools-istio.yml
#   oc create -f $HOME/lab/ftools-istio.yml
#   oc patch deploy/ftools --patch '{"spec":{"template":{"spec":{"containers":[{"name":"istio-proxy", "resources": {   "limits":{"cpu": "500m","memory": "128Mi"},"requests":{"cpu":"50m","memory":"32Mi"}   }}]}}}}'
#   oc patch deploy/ftools --patch '{"spec":{"template":{"spec":{"initContainers":[{"name":"istio-init", "resources": {   "limits":{"cpu": "500m","memory": "128Mi"},"requests":{"cpu":"50m","memory":"32Mi"}   }}]}}}}'
#   oc rollout resume deploy ftools


apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftools
  labels:
    app: ftools
spec:
  selector:
    matchLabels:
      deployment: ftools
  paused: false
  replicas: 1
  strategy:
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 1800
      updatePeriodSeconds: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: ftools
    spec:
      containers:
      - env: 
        image: quay.io/rhtgptetraining/fedoratools:2.14
        imagePullPolicy: IfNotPresent
        name: ftools
        resources:
          limits:
            cpu: 3000m
            memory: 1024Mi
          requests:
            cpu: 300m
            memory: 64Mi
